from prompts.fragments.common_rules import (
    GRAPH_TIMEOUT_GUARD,
    COMMON_RULES,
    hard_gates,
)
from prompts.fragments.tools_and_sources import (
    COMMON_TOOL_REFERENCE,
    COMMON_TOOLS_AND_SOURCES,
    GRAPH_MODES_REFERENCE,
    department_matching_rules,
    SERVICE_STANDARD_SOURCE,
)
from prompts.fragments.athena_schema import (
    ATHENA_SCHEMA_REFERENCE,
    GATS_QUESTION_COLUMN_MAP,
    GATS_COMMON_QUERY_PATTERNS,
    SQL_HARD_RULES,
)
from prompts.fragments.investigation import (
    COMMON_INVESTIGATION_METHODOLOGY,
    DBR_INVESTIGATION_METHOD,
    PROJECT_INVESTIGATION_METHOD,
    SUPPLIER_INVESTIGATION_METHOD,
    TARGETED_QUESTION_METHOD,
    SOVEREIGN_STACK_METHOD,
)
from prompts.fragments.output_specs import (
    COMMON_OUTPUT_RULES,
    COMMON_CITATION_RULES,
    SOURCE_DIAGNOSTICS,
    DBR_OUTPUT_SPEC,
    dbr_output_card,
    DEFAULT_OUTPUT_SPEC,
    PROJECT_OUTPUT_SPEC,
    PROJECT_OUTPUT_CARD,
    SUPPLIER_LOCKIN_OUTPUT_SPEC,
    SUPPLIER_LOCKIN_OUTPUT_CARD,
    SUPPLIER_ECOSYSTEM_OUTPUT_SPEC,
    SUPPLIER_ECOSYSTEM_OUTPUT_CARD,
    TARGETED_QUESTION_OUTPUT_SPEC,
    TARGETED_QUESTION_OUTPUT_CARD,
    SOVEREIGN_STACK_OUTPUT_SPEC,
    sovereign_stack_output_card,
    PITCH_DECK_OUTPUT_SPEC,
    PITCH_DECK_DESIGN_SYSTEM,
)
from prompts.fragments.query_templates import (
    dbr_required_graph_queries,
    dbr_required_athena_queries,
    dbr_web_searches,
    default_required_graph_sequence,
    PROJECT_GRAPH_QUERIES,
    PROJECT_ATHENA_QUERIES,
    PROJECT_KB_QUERIES,
    supplier_lockin_graph_queries,
    supplier_lockin_athena_queries,
    SUPPLIER_LOCKIN_KB_KEYWORDS,
    supplier_ecosystem_graph_queries,
    supplier_ecosystem_athena_queries,
    TARGETED_QUESTION_SYNONYMS,
    TARGETED_QUESTION_GRAPH_QUERIES,
    TARGETED_QUESTION_ATHENA_QUERIES,
    SOVEREIGN_STACK_DATA_COVERAGE,
    SOVEREIGN_STACK_TEMPORAL_RULES,
    SOVEREIGN_STACK_SEVEN_LAYERS,
    SOVEREIGN_STACK_CONTROL_TEST,
    SOVEREIGN_STACK_EVIDENCE_METHODOLOGY,
    SOVEREIGN_STACK_SCORING_MODEL,
    SOVEREIGN_STACK_INVESTMENT_PRIORITISATION,
    SOVEREIGN_STACK_STARTING_HYPOTHESES,
    SOVEREIGN_STACK_GRAPH_PACING,
    SOVEREIGN_STACK_PER_LAYER_STEPS,
)
from prompts.fragments.cypher_templates import (
    PROJECT_CYPHER_TEMPLATES,
    SUPPLIER_LOCKIN_CYPHER_TEMPLATES,
)
from prompts.fragments.ai_transformation import (
    AI_TRANSFORMATION_INVESTIGATION_AREAS,
    AI_TRANSFORMATION_KB_FOCUS,
    AI_TRANSFORMATION_SERVICE_STANDARD_CROSS_LENS,
    AI_TRANSFORMATION_INVESTIGATION_METHOD,
    ai_transformation_required_graph_queries,
    ai_transformation_required_athena_queries,
    ai_transformation_web_searches,
    ai_transformation_output_spec,
    # v2
    AI_TRANSFORMATION_REPORTING_DISCIPLINE,
    AI_TRANSFORMATION_REFERENCE_RULES,
    AI_TRANSFORMATION_KB_FOCUS_V2,
    ai_transformation_output_spec_v2,
)

__all__ = [
    # common rules + helpers
    "GRAPH_TIMEOUT_GUARD",
    "COMMON_RULES",
    "hard_gates",
    # tools and sources
    "COMMON_TOOL_REFERENCE",
    "COMMON_TOOLS_AND_SOURCES",
    "GRAPH_MODES_REFERENCE",
    "department_matching_rules",
    "SERVICE_STANDARD_SOURCE",
    # athena schema
    "ATHENA_SCHEMA_REFERENCE",
    "GATS_QUESTION_COLUMN_MAP",
    "GATS_COMMON_QUERY_PATTERNS",
    "SQL_HARD_RULES",
    # investigation methodology
    "COMMON_INVESTIGATION_METHODOLOGY",
    "DBR_INVESTIGATION_METHOD",
    "PROJECT_INVESTIGATION_METHOD",
    "SUPPLIER_INVESTIGATION_METHOD",
    "TARGETED_QUESTION_METHOD",
    "SOVEREIGN_STACK_METHOD",
    # output specs
    "COMMON_OUTPUT_RULES",
    "COMMON_CITATION_RULES",
    "SOURCE_DIAGNOSTICS",
    "DBR_OUTPUT_SPEC",
    "dbr_output_card",
    "DEFAULT_OUTPUT_SPEC",
    "PROJECT_OUTPUT_SPEC",
    "PROJECT_OUTPUT_CARD",
    "SUPPLIER_LOCKIN_OUTPUT_SPEC",
    "SUPPLIER_LOCKIN_OUTPUT_CARD",
    "SUPPLIER_ECOSYSTEM_OUTPUT_SPEC",
    "SUPPLIER_ECOSYSTEM_OUTPUT_CARD",
    "TARGETED_QUESTION_OUTPUT_SPEC",
    "TARGETED_QUESTION_OUTPUT_CARD",
    "SOVEREIGN_STACK_OUTPUT_SPEC",
    "sovereign_stack_output_card",
    "PITCH_DECK_OUTPUT_SPEC",
    "PITCH_DECK_DESIGN_SYSTEM",
    # query templates
    "dbr_required_graph_queries",
    "dbr_required_athena_queries",
    "dbr_web_searches",
    "default_required_graph_sequence",
    "PROJECT_GRAPH_QUERIES",
    "PROJECT_ATHENA_QUERIES",
    "PROJECT_KB_QUERIES",
    "supplier_lockin_graph_queries",
    "supplier_lockin_athena_queries",
    "SUPPLIER_LOCKIN_KB_KEYWORDS",
    "supplier_ecosystem_graph_queries",
    "supplier_ecosystem_athena_queries",
    "TARGETED_QUESTION_SYNONYMS",
    "TARGETED_QUESTION_GRAPH_QUERIES",
    "TARGETED_QUESTION_ATHENA_QUERIES",
    "SOVEREIGN_STACK_DATA_COVERAGE",
    "SOVEREIGN_STACK_TEMPORAL_RULES",
    "SOVEREIGN_STACK_SEVEN_LAYERS",
    "SOVEREIGN_STACK_CONTROL_TEST",
    "SOVEREIGN_STACK_EVIDENCE_METHODOLOGY",
    "SOVEREIGN_STACK_SCORING_MODEL",
    "SOVEREIGN_STACK_INVESTMENT_PRIORITISATION",
    "SOVEREIGN_STACK_STARTING_HYPOTHESES",
    "SOVEREIGN_STACK_GRAPH_PACING",
    "SOVEREIGN_STACK_PER_LAYER_STEPS",
    # cypher templates
    "PROJECT_CYPHER_TEMPLATES",
    "SUPPLIER_LOCKIN_CYPHER_TEMPLATES",
    # ai transformation
    "AI_TRANSFORMATION_INVESTIGATION_AREAS",
    "AI_TRANSFORMATION_KB_FOCUS",
    "AI_TRANSFORMATION_SERVICE_STANDARD_CROSS_LENS",
    "AI_TRANSFORMATION_INVESTIGATION_METHOD",
    "ai_transformation_required_graph_queries",
    "ai_transformation_required_athena_queries",
    "ai_transformation_web_searches",
    "ai_transformation_output_spec",
    # ai transformation v2
    "AI_TRANSFORMATION_REPORTING_DISCIPLINE",
    "AI_TRANSFORMATION_REFERENCE_RULES",
    "AI_TRANSFORMATION_KB_FOCUS_V2",
    "ai_transformation_output_spec_v2",
]
