"""Maps Arm's Length Body (ALB) names to their parent department.

Used when metadata only identifies the submitting organisation (e.g. an
ALB like "National Crime Agency") rather than the parent department
directly (e.g. "Home Office"). Lookups that don't find a match fall back
to using the raw name as-is — this is a best-effort mapping, not exhaustive.
"""

PARENT_MAP: dict[str, str] = {
    # --- Cabinet Office & Central ---
    "Government Property Agency": "Cabinet Office",
    "The Equality and Human Rights Commission": "Cabinet Office",
    "Office for National Statistics": "Cabinet Office",
    "Infrastructure and Projects Authority": "Cabinet Office",
    "UK Covid-19 Inquiry": "Cabinet Office",
    "Civil Service Commission": "Cabinet Office",
    "Infected Blood Compensation Authority": "Cabinet Office",
    # --- DSIT (Science, Innovation & Tech) ---
    "Government Digital Service": "Department for Science, Innovation & Technology",
    "Central Digital and Data Office": "Department for Science, Innovation & Technology",
    "Met Office": "Department for Science, Innovation & Technology",
    "UK Research and Innovation": "Department for Science, Innovation & Technology",
    "Intellectual Property Office": "Department for Science, Innovation & Technology",
    "UK Space Agency": "Department for Science, Innovation & Technology",
    # --- DfT (Transport) ---
    "Driver and Vehicle Licensing Agency": "Department for Transport",
    "Driver & Vehicle Standards Agency": "Department for Transport",
    "National Highways": "Department for Transport",
    "Network Rail": "Department for Transport",
    "Maritime & Coastguard Agency": "Department for Transport",
    "High Speed Two (HS2) Limited": "Department for Transport",
    "British Transport Police": "Department for Transport",
    "East West Rail": "Department for Transport",
    "Vehicle Certification Agency": "Department for Transport",
    # --- MoJ (Justice) & Law Officers ---
    "HM Courts & Tribunals Service": "Ministry of Justice",
    "The Crown Prosecution Service": "Attorney General's Office",
    "Serious Fraud Office": "Attorney General's Office",
    "Independent Office for Police Conduct": "Home Office",
    "Youth Justice Board": "Ministry of Justice",
    "Criminal Cases Review Commission": "Ministry of Justice",
    # --- Home Office ---
    "National Crime Agency": "Home Office",
    "Disclosure & Barring Service": "Home Office",
    "Security Industry Authority": "Home Office",
    # --- DHSC (Health) ---
    "NHS Business Services Authority": "Department of Health and Social Care",
    "UK Health Security Agency": "Department of Health and Social Care",
    "NHS Blood and Transplant": "Department of Health and Social Care",
    "Medicines and Healthcare products Regulatory Agency": "Department of Health and Social Care",
    "Genomics England": "Department of Health and Social Care",
    "Care Quality Commission": "Department of Health and Social Care",
    "NHS Property Services": "Department of Health and Social Care",
    "NHS England": "Department of Health and Social Care",
    "Health Research Authority": "Department of Health and Social Care",
    "NHS Shared Business Services": "Department of Health and Social Care",
    "NHS Resolution": "Department of Health and Social Care",
    "NHS Professionals": "Department of Health and Social Care",
    "NHS Supply Chain": "Department of Health and Social Care",
    "NHS Commercial Solutions": "Department of Health and Social Care",
    "NHS North of England Commercial Procurement Collaborative": "Department of Health and Social Care",
    "National Institute for Health and Care Excellence": "Department of Health and Social Care",
    "Food Standards Agency": "Department of Health and Social Care",
    "Ambulance Radio Programme": "Department of Health and Social Care",
    # --- DBT (Business & Trade) ---
    "British Business Bank": "Department of Business and Trade",
    "Companies House": "Department of Business and Trade",
    "Advisory, Conciliation and Arbitration Service": "Department of Business and Trade",
    "Competition and Markets Authority": "Department of Business and Trade",
    "Financial Reporting Council": "Department of Business and Trade",
    "Insolvency Service": "Department of Business and Trade",
    # --- DESNZ (Energy Security & Net Zero) ---
    "Ofgem": "Department for Energy Security and Net Zero",
    "Coal Authority": "Department for Energy Security and Net Zero",
    "UK Atomic Energy Authority": "Department for Energy Security and Net Zero",
    "North Sea Transition Authority": "Department for Energy Security and Net Zero",
    "Nuclear Decommissioning Authority": "Department for Energy Security and Net Zero",
    "UK Industrial Fusion Solutions": "Department for Energy Security and Net Zero",
    "Civil Nuclear Constabulary": "Department for Energy Security and Net Zero",
    "Salix Finance": "Department for Energy Security and Net Zero",
    # --- MHCLG (Housing/Communities) ---
    "Planning Inspectorate": "Ministry of Housing, Communities and Local Government",
    "HM Land Registry": "Ministry of Housing, Communities and Local Government",
    "Homes England": "Ministry of Housing, Communities and Local Government",
    # --- DEFRA (Environment) ---
    "Ofwat": "Department for Environment, Food and Rural Affairs",
    "Animal & Plant Health Agency": "Department for Environment, Food and Rural Affairs",
    "Environment Agency": "Department for Environment, Food and Rural Affairs",
    "Natural England": "Department for Environment, Food and Rural Affairs",
    "Marine Management Organisation": "Department for Environment, Food and Rural Affairs",
    "Rural Payments Agency": "Department for Environment, Food and Rural Affairs",
    # --- DWP (Work & Pensions) ---
    "Money and Pensions Service": "Department for Work and Pensions",
    "Health and Safety Executive": "Department for Work and Pensions",
    "The Pension Regulator": "Department for Work and Pensions",
    # --- DCMS (Culture) ---
    "Gambling Commission": "Department for Culture, Media & Sport",
    "National Lottery Heritage Fund": "Department for Culture, Media & Sport",
    "Visit Britain": "Department for Culture, Media & Sport",
    "Sport England": "Department for Culture, Media & Sport",
    "Arts Council England": "Department for Culture, Media & Sport",
    "The National Archives": "Department for Culture, Media & Sport",
    # --- MOD (Defence) ---
    "MOD Strategic Command": "Ministry of Defence",
    "Air Force": "Ministry of Defence",
    "Defence Equipment and Support": "Ministry of Defence",
    "Army": "Ministry of Defence",
    # --- HMT (Treasury) ---
    "UK Investment Bank": "HM Treasury",
    "National Savings and Investments": "HM Treasury",
    "The Valuation Office Agency": "HM Treasury",
    # --- DfE (Education) ---
    "Student Loans Company": "Department for Education",
    "Ofsted": "Department for Education",
    # --- SR21 folder abbreviations ---
    "HO": "Home Office",
    "MOD": "Ministry of Defence",
    "MoD": "Ministry of Defence",
    "DfT": "Department for Transport",
    "DfE": "Department for Education",
    "DHSC": "Department of Health and Social Care",
    "DWP": "Department for Work and Pensions",
    "HMRC": "HM Revenue and Customs",
    "HMT": "HM Treasury",
    "MoJ": "Ministry of Justice",
    "CO": "Cabinet Office",
    "DEFRA": "Department for Environment, Food and Rural Affairs",
    "Defra": "Department for Environment, Food and Rural Affairs",
    "DCMS": "Department for Culture, Media & Sport",
    "BEIS": "Department for Business, Energy & Industrial Strategy",
    "DLUHC": "Ministry of Housing, Communities and Local Government",
    "MHCLG": "Ministry of Housing, Communities and Local Government",
    "FCDO": "Foreign, Commonwealth & Development Office",
    "FCO": "Foreign, Commonwealth & Development Office",
    "DfID": "Foreign, Commonwealth & Development Office",
    "DSIT": "Department for Science, Innovation & Technology",
    "DBT": "Department of Business and Trade",
    "DESNZ": "Department for Energy Security and Net Zero",
}
