name: Release

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    uses: co-cddo/gds-idea-workflows-catalogue/.github/workflows/auto_tag_release.yml@main
    secrets: inherit
